VK_NAMES = [
    'UNDEF_0x00',
    'VK_LBUTTON',
    'VK_RBUTTON',
    'VK_CANCEL',
    'VK_MBUTTON',
    'VK_XBUTTON1',
    'VK_XBUTTON2',
    'UNDEF_0x07',
    'VK_BACK',
    'VK_TAB',
    'UNDEF_0x0A',
    'UNDEF_0x0B',
    'VK_CLEAR',
    'VK_RETURN',
    'UNDEF_0x0E',
    'UNDEF_0x0F',
    'VK_SHIFT',
    'VK_CONTROL',
    'VK_MENU',
    'VK_PAUSE',
    'VK_CAPITAL',
    'VK_HANGUL',
    'VK_IME_ON',
    'VK_JUNJA',
    'VK_FINAL',
    'VK_KANJI',
    'VK_IME_OFF',
    'VK_ESCAPE',
    'VK_CONVERT',
    'VK_NONCONVERT',
    'VK_ACCEPT',
    'VK_MODECHANGE',
    'VK_SPACE',
    'VK_PRIOR',
    'VK_NEXT',
    'VK_END',
    'VK_HOME',
    'VK_LEFT',
    'VK_UP',
    'VK_RIGHT',
    'VK_DOWN',
    'VK_SELECT',
    'VK_PRINT',
    'VK_EXECUTE',
    'VK_SNAPSHOT',
    'VK_INSERT',
    'VK_DELETE',
    'VK_HELP',
    'VK_0',
    'VK_1',
    'VK_2',
    'VK_3',
    'VK_4',
    'VK_5',
    'VK_6',
    'VK_7',
    'VK_8',
    'VK_9',
    'UNDEF_0x3A',
    'UNDEF_0x3B',
    'UNDEF_0x3C',
    'UNDEF_0x3D',
    'UNDEF_0x3E',
    'UNDEF_0x3F',
    'UNDEF_0x40',
    'VK_A',
    'VK_B',
    'VK_C',
    'VK_D',
    'VK_E',
    'VK_F',
    'VK_G',
    'VK_H',
    'VK_I',
    'VK_J',
    'VK_K',
    'VK_L',
    'VK_M',
    'VK_N',
    'VK_O',
    'VK_P',
    'VK_Q',
    'VK_R',
    'VK_S',
    'VK_T',
    'VK_U',
    'VK_V',
    'VK_W',
    'VK_X',
    'VK_Y',
    'VK_Z',
    'VK_LWIN',
    'VK_RWIN',
    'VK_APPS',
    'UNDEF_0x5E',
    'VK_SLEEP',
    'VK_NUMPAD0',
    'VK_NUMPAD1',
    'VK_NUMPAD2',
    'VK_NUMPAD3',
    'VK_NUMPAD4',
    'VK_NUMPAD5',
    'VK_NUMPAD6',
    'VK_NUMPAD7',
    'VK_NUMPAD8',
    'VK_NUMPAD9',
    'VK_MULTIPLY',
    'VK_ADD',
    'VK_SEPARATOR',
    'VK_SUBTRACT',
    'VK_DECIMAL',
    'VK_DIVIDE',
    'VK_F1',
    'VK_F2',
    'VK_F3',
    'VK_F4',
    'VK_F5',
    'VK_F6',
    'VK_F7',
    'VK_F8',
    'VK_F9',
    'VK_F10',
    'VK_F11',
    'VK_F12',
    'VK_F13',
    'VK_F14',
    'VK_F15',
    'VK_F16',
    'VK_F17',
    'VK_F18',
    'VK_F19',
    'VK_F20',
    'VK_F21',
    'VK_F22',
    'VK_F23',
    'VK_F24',
    'VK_NAVIGATION_VIEW',
    'VK_NAVIGATION_MENU',
    'VK_NAVIGATION_UP',
    'VK_NAVIGATION_DOWN',
    'VK_NAVIGATION_LEFT',
    'VK_NAVIGATION_RIGHT',
    'VK_NAVIGATION_ACCEPT',
    'VK_NAVIGATION_CANCEL',
    'VK_NUMLOCK',
    'VK_SCROLL',
    'VK_OEM_NEC_EQUAL',
    'VK_OEM_FJ_MASSHOU',
    'VK_OEM_FJ_TOUROKU',
    'VK_OEM_FJ_LOYA',
    'VK_OEM_FJ_ROYA',
    'UNDEF_0x97',
    'UNDEF_0x98',
    'UNDEF_0x99',
    'UNDEF_0x9A',
    'UNDEF_0x9B',
    'UNDEF_0x9C',
    'UNDEF_0x9D',
    'UNDEF_0x9E',
    'UNDEF_0x9F',
    'VK_LSHIFT',
    'VK_RSHIFT',
    'VK_LCONTROL',
    'VK_RCONTROL',
    'VK_LMENU',
    'VK_RMENU',
    'VK_BROWSER_BACK',
    'VK_BROWSER_FORWARD',
    'VK_BROWSER_REFRESH',
    'VK_BROWSER_STOP',
    'VK_BROWSER_SEARCH',
    'VK_BROWSER_FAVORITES',
    'VK_BROWSER_HOME',
    'VK_VOLUME_MUTE',
    'VK_VOLUME_DOWN',
    'VK_VOLUME_UP',
    'VK_MEDIA_NEXT_TRACK',
    'VK_MEDIA_PREV_TRACK',
    'VK_MEDIA_STOP',
    'VK_MEDIA_PLAY_PAUSE',
    'VK_LAUNCH_MAIL',
    'VK_LAUNCH_MEDIA_SELECT',
    'VK_LAUNCH_APP1',
    'VK_LAUNCH_APP2',
    'UNDEF_0xB8',
    'UNDEF_0xB9',
    'VK_OEM_1',
    'VK_OEM_PLUS',
    'VK_OEM_COMMA',
    'VK_OEM_MINUS',
    'VK_OEM_PERIOD',
    'VK_OEM_2',
    'VK_OEM_3',
    'VK_ABNT_C1',
    'VK_ABNT_C2',
    'VK_GAMEPAD_A',
    'VK_GAMEPAD_B',
    'VK_GAMEPAD_X',
    'VK_GAMEPAD_Y',
    'VK_GAMEPAD_RIGHT_SHOULDER',
    'VK_GAMEPAD_LEFT_SHOULDER',
    'VK_GAMEPAD_LEFT_TRIGGER',
    'VK_GAMEPAD_RIGHT_TRIGGER',
    'VK_GAMEPAD_DPAD_UP',
    'VK_GAMEPAD_DPAD_DOWN',
    'VK_GAMEPAD_DPAD_LEFT',
    'VK_GAMEPAD_DPAD_RIGHT',
    'VK_GAMEPAD_MENU',
    'VK_GAMEPAD_VIEW',
    'VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON',
    'VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON',
    'VK_GAMEPAD_LEFT_THUMBSTICK_UP',
    'VK_GAMEPAD_LEFT_THUMBSTICK_DOWN',
    'VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT',
    'VK_GAMEPAD_LEFT_THUMBSTICK_LEFT',
    'VK_GAMEPAD_RIGHT_THUMBSTICK_UP',
    'VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN',
    'VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT',
    'VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT',
    'VK_OEM_4',
    'VK_OEM_5',
    'VK_OEM_6',
    'VK_OEM_7',
    'VK_OEM_8',
    'UNDEF_0xE0',
    'VK_OEM_AX',
    'VK_OEM_102',
    'VK_ICO_HELP',
    'VK_ICO_00',
    'VK_PROCESSKEY',
    'VK_ICO_CLEAR',
    'VK_PACKET',
    'UNDEF_0xE8',
    'VK_OEM_RESET',
    'VK_OEM_JUMP',
    'VK_OEM_PA1',
    'VK_OEM_PA2',
    'VK_OEM_PA3',
    'VK_OEM_WSCTRL',
    'VK_OEM_CUSEL',
    'VK_OEM_ATTN',
    'VK_OEM_FINISH',
    'VK_OEM_COPY',
    'VK_OEM_AUTO',
    'VK_OEM_ENLW',
    'VK_OEM_BACKTAB',
    'VK_ATTN',
    'VK_CRSEL',
    'VK_EXSEL',
    'VK_EREOF',
    'VK_PLAY',
    'VK_ZOOM',
    'VK_NONAME',
    'VK_PA1',
    'VK_OEM_CLEAR',
    'VK__none_',
]
VK_LBUTTON = 1
VK_RBUTTON = 2
VK_CANCEL = 3
VK_MBUTTON = 4
VK_XBUTTON1 = 5
VK_XBUTTON2 = 6
VK_BACK = 8
VK_TAB = 9
VK_CLEAR = 12
VK_RETURN = 13
VK_SHIFT = 16
VK_CONTROL = 17
VK_MENU = 18
VK_PAUSE = 19
VK_CAPITAL = 20
VK_HANGUL = 21
VK_IME_ON = 22
VK_JUNJA = 23
VK_FINAL = 24
VK_KANJI = 25
VK_IME_OFF = 26
VK_ESCAPE = 27
VK_CONVERT = 28
VK_NONCONVERT = 29
VK_ACCEPT = 30
VK_MODECHANGE = 31
VK_SPACE = 32
VK_PRIOR = 33
VK_NEXT = 34
VK_END = 35
VK_HOME = 36
VK_LEFT = 37
VK_UP = 38
VK_RIGHT = 39
VK_DOWN = 40
VK_SELECT = 41
VK_PRINT = 42
VK_EXECUTE = 43
VK_SNAPSHOT = 44
VK_INSERT = 45
VK_DELETE = 46
VK_HELP = 47
VK_0 = 48
VK_1 = 49
VK_2 = 50
VK_3 = 51
VK_4 = 52
VK_5 = 53
VK_6 = 54
VK_7 = 55
VK_8 = 56
VK_9 = 57
VK_A = 65
VK_B = 66
VK_C = 67
VK_D = 68
VK_E = 69
VK_F = 70
VK_G = 71
VK_H = 72
VK_I = 73
VK_J = 74
VK_K = 75
VK_L = 76
VK_M = 77
VK_N = 78
VK_O = 79
VK_P = 80
VK_Q = 81
VK_R = 82
VK_S = 83
VK_T = 84
VK_U = 85
VK_V = 86
VK_W = 87
VK_X = 88
VK_Y = 89
VK_Z = 90
VK_LWIN = 91
VK_RWIN = 92
VK_APPS = 93
VK_SLEEP = 95
VK_NUMPAD0 = 96
VK_NUMPAD1 = 97
VK_NUMPAD2 = 98
VK_NUMPAD3 = 99
VK_NUMPAD4 = 100
VK_NUMPAD5 = 101
VK_NUMPAD6 = 102
VK_NUMPAD7 = 103
VK_NUMPAD8 = 104
VK_NUMPAD9 = 105
VK_MULTIPLY = 106
VK_ADD = 107
VK_SEPARATOR = 108
VK_SUBTRACT = 109
VK_DECIMAL = 110
VK_DIVIDE = 111
VK_F1 = 112
VK_F2 = 113
VK_F3 = 114
VK_F4 = 115
VK_F5 = 116
VK_F6 = 117
VK_F7 = 118
VK_F8 = 119
VK_F9 = 120
VK_F10 = 121
VK_F11 = 122
VK_F12 = 123
VK_F13 = 124
VK_F14 = 125
VK_F15 = 126
VK_F16 = 127
VK_F17 = 128
VK_F18 = 129
VK_F19 = 130
VK_F20 = 131
VK_F21 = 132
VK_F22 = 133
VK_F23 = 134
VK_F24 = 135
VK_NAVIGATION_VIEW = 136
VK_NAVIGATION_MENU = 137
VK_NAVIGATION_UP = 138
VK_NAVIGATION_DOWN = 139
VK_NAVIGATION_LEFT = 140
VK_NAVIGATION_RIGHT = 141
VK_NAVIGATION_ACCEPT = 142
VK_NAVIGATION_CANCEL = 143
VK_NUMLOCK = 144
VK_SCROLL = 145
VK_OEM_NEC_EQUAL = 146
VK_OEM_FJ_MASSHOU = 147
VK_OEM_FJ_TOUROKU = 148
VK_OEM_FJ_LOYA = 149
VK_OEM_FJ_ROYA = 150
VK_LSHIFT = 160
VK_RSHIFT = 161
VK_LCONTROL = 162
VK_RCONTROL = 163
VK_LMENU = 164
VK_RMENU = 165
VK_BROWSER_BACK = 166
VK_BROWSER_FORWARD = 167
VK_BROWSER_REFRESH = 168
VK_BROWSER_STOP = 169
VK_BROWSER_SEARCH = 170
VK_BROWSER_FAVORITES = 171
VK_BROWSER_HOME = 172
VK_VOLUME_MUTE = 173
VK_VOLUME_DOWN = 174
VK_VOLUME_UP = 175
VK_MEDIA_NEXT_TRACK = 176
VK_MEDIA_PREV_TRACK = 177
VK_MEDIA_STOP = 178
VK_MEDIA_PLAY_PAUSE = 179
VK_LAUNCH_MAIL = 180
VK_LAUNCH_MEDIA_SELECT = 181
VK_LAUNCH_APP1 = 182
VK_LAUNCH_APP2 = 183
VK_OEM_1 = 186
VK_OEM_PLUS = 187
VK_OEM_COMMA = 188
VK_OEM_MINUS = 189
VK_OEM_PERIOD = 190
VK_OEM_2 = 191
VK_OEM_3 = 192
VK_ABNT_C1 = 193
VK_ABNT_C2 = 194
VK_GAMEPAD_A = 195
VK_GAMEPAD_B = 196
VK_GAMEPAD_X = 197
VK_GAMEPAD_Y = 198
VK_GAMEPAD_RIGHT_SHOULDER = 199
VK_GAMEPAD_LEFT_SHOULDER = 200
VK_GAMEPAD_LEFT_TRIGGER = 201
VK_GAMEPAD_RIGHT_TRIGGER = 202
VK_GAMEPAD_DPAD_UP = 203
VK_GAMEPAD_DPAD_DOWN = 204
VK_GAMEPAD_DPAD_LEFT = 205
VK_GAMEPAD_DPAD_RIGHT = 206
VK_GAMEPAD_MENU = 207
VK_GAMEPAD_VIEW = 208
VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON = 209
VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON = 210
VK_GAMEPAD_LEFT_THUMBSTICK_UP = 211
VK_GAMEPAD_LEFT_THUMBSTICK_DOWN = 212
VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT = 213
VK_GAMEPAD_LEFT_THUMBSTICK_LEFT = 214
VK_GAMEPAD_RIGHT_THUMBSTICK_UP = 215
VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN = 216
VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT = 217
VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT = 218
VK_OEM_4 = 219
VK_OEM_5 = 220
VK_OEM_6 = 221
VK_OEM_7 = 222
VK_OEM_8 = 223
VK_OEM_AX = 225
VK_OEM_102 = 226
VK_ICO_HELP = 227
VK_ICO_00 = 228
VK_PROCESSKEY = 229
VK_ICO_CLEAR = 230
VK_PACKET = 231
VK_OEM_RESET = 233
VK_OEM_JUMP = 234
VK_OEM_PA1 = 235
VK_OEM_PA2 = 236
VK_OEM_PA3 = 237
VK_OEM_WSCTRL = 238
VK_OEM_CUSEL = 239
VK_OEM_ATTN = 240
VK_OEM_FINISH = 241
VK_OEM_COPY = 242
VK_OEM_AUTO = 243
VK_OEM_ENLW = 244
VK_OEM_BACKTAB = 245
VK_ATTN = 246
VK_CRSEL = 247
VK_EXSEL = 248
VK_EREOF = 249
VK_PLAY = 250
VK_ZOOM = 251
VK_NONAME = 252
VK_PA1 = 253
VK_OEM_CLEAR = 254
VK__none_ = 255